---
title: "simpleRegress"
author: "Connor Rice"
date: "Fall 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## make a simple regression model

```{r}
bears <- read.csv(file="BEARS.csv",header = TRUE)
#adjust factors to be factors
bears$SEX<- as.factor(bears$SEX)
bears$MONTH<- as.factor(bears$MONTH)
```

## Model LENGTH ~ NECK  this is an example  

```{r}
simp <- lm(LENGTH~NECK,data=bears)
plot(LENGTH~NECK,data=bears)
abline(simp)
summary.lm(simp)
```
RSE: 5.376 ARS: 0.7476


## Compare all models that predict LENGTH other than NECK. Then order them from worst to best by its value of Adjusted-Rsquared (bigger is better), or by RSE (residual standard error) where smaller is better. 

```{r}
simp1 <- lm(LENGTH~AGE,data=bears)
plot(LENGTH~AGE,data=bears)
abline(simp1)
summary.lm(simp1)
```

RSE: 7.511 ARS: 0.5073

```{r}
simp2 <- lm(LENGTH~HEADLEN,data=bears)
plot(LENGTH~HEADLEN,data=bears)
abline(simp2)
summary.lm(simp2)
```

RSE: 4.235 ARS: 0.8434

```{r}
simp3 <- lm(LENGTH~HEADWTH,data=bears)
plot(LENGTH~HEADWTH,data=bears)
abline(simp3)
summary.lm(simp3)
```

RSE: 7.32 ARS: 0.5321
